# config.py
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
COLLECTABLES_SPAWN_RATE = 500  # ms between collectibles spawns
ASTEROID_SPAWN_RATE = 1000  # ms between asteroid spawns
PLAYER_SPEED = 5
COLLECTABLES_SPEED = 2
ASTEROID_SPEED = 3
COLOR_START = ()
COLOR_END = ()
TEXT_COLOR = (255, 255, 255)
HEALTH_BAR_COLOR = (0, 200, 0) 